### ISSUE TITLE
Nexus workflow for QE with hybrid DFT

### ISSUE THREAD

**Issue by aannabe** [QMCPACK/nexus_training#4]
Hi @jtkrogel , is there an example/guide of Nexus workflow for hybrids as the QE NSCF step isn't possible? Specifically, is the tiling of the wavefunction supported?

**Comment by jtkrogel** [comment]
Sorry, for some reason I only just now got a notification for this.

You should be able to build off of this example:

https://github.com/QMCPACK/qmcpack/blob/develop/nexus/examples/qmcpack/rsqmc_quantum_espresso/01_diamond_dft_vmc/diamond_lda_vmc.py

Remove the NSCF part and instead point pw2qmcpack to depend on the SCF calculation for the orbitals.  Update the SCF part with inputs for a hybrid calculation, remove `kgrid` and `kshift`, and then add `nosym=True`.  

This will force the hybrid calculation to proceed only on the k-points required to construct the tiled supercell, and, if specified, its twist angles (supercell k-points provided as `kgrid` and `kshift` to `generate_physical_system`.

Let me know if you run into any issues with this.

**Comment by aannabe** [comment]
Thanks. Closing the issue.
